org: cristopherz
app: nodejs-projects
service: aws-node-express-api-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  stage: release
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
